---

# Ensure the log directory and file exists
- name: Ensure /var/log directory exists
  ansible.builtin.file:
    path: /var/log
    state: directory
    mode: '0755'

- name: Check if {{ pika_log_file }} exists
  ansible.builtin.stat:
    path: "{{ pika_log_file }}"
  register: pika_log_file_stat

- name: Create {{ pika_log_file }} if it does not exist
  ansible.builtin.file:
    path: "{{ pika_log_file }}"
    state: touch
    mode: '0666'
  when: not pika_log_file_stat.stat.exists  

- name: Ensure correct permissions on {{ pika_log_file }}
  ansible.builtin.file:
    path: "{{ pika_log_file }}"
    mode: '0666'
  when: pika_log_file_stat.stat.exists and pika_log_file_stat.stat.mode != '0666'

- name: Ensure the pre-backup script is present
  ansible.builtin.template:
    src: pre_backup.sh.j2
    dest: "{{ pre_backup_script_location }}"
    mode: '0755'

- name: Install Flatpak
  ansible.builtin.dnf:
    name: flatpak
    state: present

- name: Add Flathub repository
  ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  register: result
  failed_when: "'remote-add' in result.stderr"

- name: Check if Pika Backup is already installed
  ansible.builtin.shell: flatpak list | grep org.gnome.World.PikaBackup
  register: pika_installed
  ignore_errors: true

- name: Install Pika Backup
  ansible.builtin.command: flatpak install -y flathub org.gnome.World.PikaBackup
  when: pika_installed.rc != 0

- name: Ensure the Pika Backup service override directory exists
  ansible.builtin.file:
    path: /etc/systemd/system/pika-backup.service.d
    state: directory

- name: Configure Pika Backup to use pre-backup script
  ansible.builtin.copy:
    dest: /etc/systemd/system/pika-backup.service.d/override.conf
    content: |
      [Service]
      ExecStartPre="{{ pre_backup_script_location }}"
  notify: reload systemd
