---

# Ensure the log directory and file exists
- name: Ensure /var/log directory exists
  ansible.builtin.file:
    path: /var/log
    state: directory
    mode: '0755'

- name: Ensure /var/log/nas_mount.log exists and has correct permissions
  ansible.builtin.file:
    path: "{{ log_file }}"
    state: touch
    mode: '0666'

- name: Ensure the pre-backup script is present
  copy:
    src: pre_backup.sh
    dest: /usr/local/bin/pre_backup.sh
    mode: '0755'

- name: Install Flatpak
  dnf:
    name: flatpak
    state: present

- name: Add Flathub repository
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  register: result
  failed_when: "'remote-add' in result.stderr"

- name: Check if Pika Backup is already installed
  command: flatpak list | grep org.gnome.World.PikaBackup
  register: pika_installed
  ignore_errors: true

- name: Install Pika Backup
  command: flatpak install -y flathub org.gnome.World.PikaBackup
  when: pika_installed.rc != 0

- name: Ensure the Pika Backup service override directory exists
  file:
    path: /etc/systemd/system/pika-backup.service.d
    state: directory

- name: Configure Pika Backup to use pre-backup script
  copy:
    dest: /etc/systemd/system/pika-backup.service.d/override.conf
    content: |
      [Service]
      ExecStartPre=/usr/local/bin/pre_backup.sh
  notify: reload systemd
